# for more information on how to install requests
# http://docs.python-requests.org/en/master/user/install/#install
import requests
import json

# read in the user word from the text file generated by the Java code

# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# f = open("C:\\Users\\Thomas\\Desktop\\NewCountdown\\ScrabbleProject\\src\\main\\java\\ie\\gmit\\sw\\Game\\output.txt", "r")

f = open("C:\\Users\\Thomas\\Desktop\\MajoCountdown\\CountdownProject\\src\\ie\\gmit\\sw\\output.txt", "r")

# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

#print(f.read())

if f.mode == 'r':
        contents = f.read()


# TODO: replace with your own app_id and app_key
app_id = '49bd1907'
app_key = 'a5d88cdfc2e208b0b5c15ee7d74c7e4f'

language = 'en'
word_id = contents

url = 'https://od-api.oxforddictionaries.com:443/api/v1/entries/' + language + '/' + word_id.lower()

r = requests.get(url, headers = {'app_id': app_id, 'app_key': app_key})
#print (r)

#defin = json.loads(r.json()['definitions'])



print("code {}\n".format(r.status_code))
#print("text \n" + r.text)
#print("text \n" + defin)
#r.json()['definitions']
#r['text']['definitions']
#print("json \n" + json.dumps(r.json()))

# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# f = open("C:\\Users\\Thomas\\Desktop\\NewCountdown\\ScrabbleProject\\src\\main\\java\\ie\\gmit\\sw\\Game\\outputCode.txt", "w")

f = open("C:\\Users\\Thomas\\Desktop\\MajoCountdown\\CountdownProject\\src\\ie\\gmit\\sw\\outputCode.txt", "w")
  
# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
f.write(format(r.status_code))
f.close()