# for more information on how to install requests
# http://docs.python-requests.org/en/master/user/install/#install
import requests
import json

# how to use relative path
# https://medium.com/@ageitgey/python-3-quick-tip-the-easy-way-to-deal-with-file-paths-on-windows-mac-and-linux-11a072b58d5f
# https://stackoverflow.com/questions/1270951/how-to-refer-to-relative-paths-of-resources-when-working-with-a-code-repository
from pathlib import Path

# read in the user word from the text file generated by the Java code
output_file = Path(__file__).parent / "output.txt"
f = open(output_file, "r")

if f.mode == 'r':
        contents = f.read()

# TODO: replace with your own app_id and app_key
app_id = '49bd1907'
app_key = 'a5d88cdfc2e208b0b5c15ee7d74c7e4f'

language = 'en'
word_id = contents

url = 'https://od-api.oxforddictionaries.com:443/api/v1/entries/' + language + '/' + word_id.lower()

r = requests.get(url, headers = {'app_id': app_id, 'app_key': app_key})

print("code {}\n".format(r.status_code))
f.close()

output_code_file = Path(__file__).parent / "outputCode.txt"
f = open(output_code_file, "w")
f.write(format(r.status_code))
f.close()